-- supabase_schema.sql
-- Create posts table used by collectors
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform text,
  source_name text,
  source_url text,
  post_id text,
  post_url text,
  author text,
  text text,
  language text,
  datetime_utc timestamptz,
  datetime_local text,
  admin_area text,
  locality text,
  geofenced_area text,
  tension_level text,
  media_urls text,
  shares text,
  likes text,
  comments text,
  collected_at_utc timestamptz,
  collector text,
  hash text UNIQUE,
  notes text
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_posts_collected_at ON public.posts (collected_at_utc);
CREATE INDEX IF NOT EXISTS idx_posts_tension ON public.posts (tension_level);
